### ISSUE TITLE
Create order filter for printing actions

### ISSUE THREAD

**Issue by alexmigf** [wpovernight/woocommerce-pdf-invoices-packing-slips#198]
Currently we don't have a way to know when a document is printed, but would be nice if we could do that and also add a filter in the orders list to get printed or non-printed orders for each type of document.

Forum ticket: https://wordpress.org/support/topic/new-filter-in-orders-page/?view=all

**Comment by alexmigf** [comment]
We could add a new meta, for example `_wcpdf_invoice_prints` where we could count the number of times someone clicks the PDF buttons, and add in the order sidebar a way to reset the counter or mark as not printed.

We could also implement this: https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/pull/144#issue-568291457

@Spreeuw what you think?

**Comment by Spreeuw** [comment]
I think for the data itself, the `last_printed` with a date is perhaps more useful than a number of `prints`. I think we should be smart about what to count as 'printing', and make this filterable in some way, because some people may only want to mark it printed when it's opened via the backend bulk actions or single buttons (action list or order details page), but others may have a setup that prints email attachments (with a printer email address) or even third party automatic printing. So I think determining the context of the call is one of the main challenges here. We could then have a filter around an array of contexts that are considered 'printing'. For email people may want to count some emails as printed and others not, so we may need to have an additional, more fine grained control filter to determine whether it is a print action based on all the context parameters we have.

**Comment by alexmigf** [comment]
We already have use contexts to save the creation order note: https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/master/includes/class-wcpdf-main.php#L934-L976

We could use that to build something for the print too. What you think?

**Comment by rodolphebertozzo** [comment]
+1
