### ISSUE TITLE
Load custom fonts in DOMPDF merging with local or vendor fonts

### ISSUE THREAD

**Issue by alexmigf** [wpovernight/woocommerce-pdf-invoices-packing-slips#230]
Currently we pass a cache file `dompdf_font_family_cache.php` directly to the `vendor/dompdf/dompdf/lib/fonts` directory and also our custom fonts as well. This is not ideal because every time we need to upgrade DOMPDF we need to copy this.

#### Things we should address:

* Move our custom fonts to a dedicated plugin directory, I suggest: `assets/fonts`
* Copy the custom fonts to the local (uploads folder) fonts
* Load the uploads fonts directory as the `fontDir`

**Comment by Spreeuw** [comment]
More specifically, this is referring to the following procedure, which is triggered 1) when the tmp folder is initiated ([here](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/1b97c0589293bc36167f5ae99d9f8684cdabdc21/includes/class-wcpdf-main.php#L580-L583)) and 2) when the plugin is updated ([here](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/1b97c0589293bc36167f5ae99d9f8684cdabdc21/includes/class-wcpdf-install.php#L206)):
https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/1b97c0589293bc36167f5ae99d9f8684cdabdc21/includes/class-wcpdf-main.php#L704-L730

dompdf actually has merging code built-in:
https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/1b97c0589293bc36167f5ae99d9f8684cdabdc21/vendor/dompdf/dompdf/src/FontMetrics.php#L123-L151

And I think we should use this as much as possible. In theory (I have not verified this with tests), with the above dompdf function, our own merge function shouldn't even be necessary because dompdf will merge it automatically.

However, when we introduce a third font source (our own 'custom' fonts that are not distributed with dompdf), we still need to merge them with the local fonts.

I think it could work like this:

1. We load our own custom font list in the in the `FontMetrics` class, then change the font folder to the local WCPDF tmp folder (using `setOptions()`) and call `saveFontFamilies()` so that the merged result is saved there.
2. Then, when we load dompdf as we do now, dompdf will automatically merge those fonts with the distributed fonts.

We need to keep https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/pull/176 in mind - not that particular solution, but the fact that if we no longer place our custom fonts inside the vendor folder, and the fonts folder is not writable, the fallback no longer works as well as it does now (since the vendor folder will not have Open Sans for example). So in those cases it should have a fallback to our bundled/custom fonts.

**Comment by alexmigf** [comment]
Ho should be called the wrapper class? `class-wcpdf-dompdf-wrapper.php`?

**Comment by alexmigf** [comment]
`fontMetrics` class is different from version 1.0 to 1.1, specially the `loadFontFamilies` method, which in the newer version uses the closures. Did you saw that when commenting above?

**Comment by Spreeuw** [comment]
Yes I saw that, but it also has a fallback to the array:
https://github.com/dompdf/dompdf/blob/aa594c1cdbcdab04977fdd0fff669a017fb50ef4/src/FontMetrics.php#L144

Was there a specific problem you ran into?

**Comment by alexmigf** [comment]
I was first trying using the current version, but the merging using `fontDir` just happens using the last version `1.1`, otherwise it points to 'rootDir'.

**Comment by Spreeuw** [comment]
That's strange, are you sure you're calling it correctly? As you can see in the code snippet in my comment above (which links to the code present in the current release of `woocommerce-pdf-invoices-packing-slips`), the merge code is there too:
https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/issues/230#issuecomment-972835273

Or comparing from dompdf directly: [1.0.2](https://github.com/dompdf/dompdf/blob/8768448244967a46d6e67b891d30878e0e15d25c/src/FontMetrics.php#L123-L151) vs [1.1.0](https://github.com/dompdf/dompdf/blob/aa594c1cdbcdab04977fdd0fff669a017fb50ef4/src/FontMetrics.php#L125-L155)

The only difference between these two versions is the usage of the closure and `$this->options` vs `$this->getOptions()`

Can you push your code to a branch and create a Draft PR? Then we can also see the contents of the cache files your using.

**Comment by Spreeuw** [comment]
I looked closer into the current Dompdf merge methods inside the `FontMetrics` class and realized that they're not suitable for want we want to do.

## 1. It doesn't copy font files ##
The code in `saveFontFamilies` only handles merging the `dompdf_font_family_cache.dist.php` file with the `dompdf_font_family_cache.php` file. The font files themselves still need to be moved if we want to store them locally.

## 2. Paths are not adapted when merging "cache" files ##
When the contents of the `dompdf_font_family_cache.dist.php` and `dompdf_font_family_cache.php` files are merged, the paths themselves don't change (which makes sense given point 1. above). The problem with this is that if we trick dompdf into loading our fonts by temporarily setting the `rootDir` option to our plugin fonts, it will include those into the local (`/wp-content/etc...`) cache file with a relative path to `rootDir`. If we then revert to the original `rootDir`, those files will not exist in that folder, so dompdf will no longer be able to load them.

The result of this is that we still need custom code to copy fonts and rewrite paths anyway, and there is no advantage to utilizing the `FontMetrics` class to do this for us.

**Comment by Spreeuw** [comment]
@alexmigf I've made a first attempt at creating a more robust font synchronization class, could you take a look at it?
https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/tree/improved-font-synchronization

**Comment by alexmigf** [comment]
This is going to copy our fonts but not the DOMPDF ones?

**Comment by Spreeuw** [comment]
Exactly, because dompdf merges the local fonts with the bundled fonts in its fontmetrics class: https://github.com/dompdf/dompdf/blob/aa594c1cdbcdab04977fdd0fff669a017fb50ef4/src/FontMetrics.php#L134-L154

So it then ends up with a list that is a mix of paths in both the local `$fontDir` as well as `$rootDir . "/lib/fonts/"`

**Comment by alexmigf** [comment]
You didn't remove our fonts from the DOMPDF `fonts` folder, was on propose?

**Comment by Spreeuw** [comment]
No, for now this was just testing the mechanism, I'll push a version without our own fonts in a minute

**Comment by alexmigf** [comment]
The tests I did so far seems to working fine.

**Comment by Spreeuw** [comment]
> I'll push a version without our own fonts in a minute

Done! https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/commit/178535e899ea3697256fd5e58ab2a91f19b4c861

**Comment by alexmigf** [comment]
If I load a custom font, it is supposed to merge the DOMPDF fonts in the cache file?

**Comment by Spreeuw** [comment]
If you load a custom font (by which I assume you mean: 'installing' a custom font via CSS, then creating a PDF with that font), it should be added to the cache file in the local folder.

Is that not working currently? A bit more information behind your question would help ;)

To be clear: the code in that branch is just for making sure the plugin fonts are updated when the plugin is updated. Everything else is purely dompdf.

**Comment by alexmigf** [comment]
> If you load a custom font (by which I assume you mean: 'installing' a custom font via CSS, then creating a PDF with that font), it should be added to the cache file in the local folder.

It is, but also the DOMPDF fonts, which wasn't there (only plugin fonts)

**Comment by Spreeuw** [comment]
just the cache file I suppose, still linked to `$rootDir`? Can you share your results?

**Comment by alexmigf** [comment]
#### Test 1

Plugins fonts copied to local folder
Cache file created in local folder with plugin fonts in it linked to `$fontDir`

#### Test 2

Install custom font
Cache file updated:
* Plugin fonts linked to `$fontDir`
* DOMPDF fonts added linked to `$rootDir`
* Custom font added linked to `$fontDir`

**Comment by Spreeuw** [comment]
Seems fine, doesn't it? Should I create a PR for further testing?

**Comment by alexmigf** [comment]
Sure, do it!
