### ISSUE TITLE
[v2.0-b5] Translation of Premium Templates not properly working

### ISSUE THREAD

**Issue by thomas-zg** [wpovernight/woocommerce-pdf-invoices-packing-slips#27]
The premium templates are not properly translated to DE. While the Simple template is working, the Simple Premium has a number of elements which are not translated.

The site language is de_DE, premium template version is 2.4.0-beta-1.

I removed some parts of the PDF because it's a copy of my production database.
[Rechnung-2017-00540.pdf](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/files/1083346/Rechnung-2017-00540.pdf)

**Comment by thomas-zg** [comment]
This only happen when I turn of the legacy mode.

**Comment by Spreeuw** [comment]
Thanks for the heads up! Indeed I haven't updated the strings in the premium templates yet, they are using the old `wpo_wcpdf` textdomain rather than the wordpress standard `woocommerce-pdf-invoices-packing-slips` which is the plugin slug. With this new textdomain, translations can be [maintained via wordpress.org](https://translate.wordpress.org/projects/wp-plugins/woocommerce-pdf-invoices-packing-slips).

I will update the strings in the premium templates, meanwhile indeed using legacy mode should fix this (this loads same translation files twice, once for the old textdomain and once for the new textdomain).

Closing this issue for now as this is about the premium templates so I can't close it with a commit here.
