### ISSUE TITLE
Restyle the settings document tabs

### ISSUE THREAD

**Issue by alexmigf** [wpovernight/woocommerce-pdf-invoices-packing-slips#277]
by @Terminator-Barbapapa 

> Restyle the document tabs at WooCommerce > PDF Invoices > Documents

**Comment by alexmigf** [comment]
![Captura de ecrã de 2022-01-06 16-44-08](https://user-images.githubusercontent.com/533273/148418430-a55e8f3a-08dc-42e8-b820-1977d57120d7.png)

**Comment by Spreeuw** [comment]
I think @Terminator-Barbapapa had something different in mind, this was in his mockup:
![document-select-mockup](https://user-images.githubusercontent.com/3217773/148538931-79b62641-ff7f-4aac-b532-1b168a66fca0.png)

@alexmigf I'm worried that your solution may become a bit crowded if there are more documents and it's shown in "Sidebar" mode.

**Comment by alexmigf** [comment]
@Spreeuw should I clean what I did or implement like that screenshot?

**Comment by alexmigf** [comment]
![Captura de ecrã de 2022-01-07 16-36-44](https://user-images.githubusercontent.com/533273/148576363-99ae1b57-cee8-4d3b-bf19-2d0c77b8dc65.png)

**Comment by Spreeuw** [comment]
@Terminator-Barbapapa You mentioned on slack you were going to push some improvements here, but I'm not sure this you still have this on deck because it was moved to 'Needs review' so it's now back to 'In Progress'

I see a few issues:

- only the text itself is clickable, but the whole line highlights so I would expect the whole line to be clickable
- The triangle is a bit too big compared to the text
- I'm not sure about the 'select' text
