### ISSUE TITLE
Number Store table not created

### ISSUE THREAD

**Issue by alexmigf** [wpovernight/woocommerce-pdf-invoices-packing-slips#291]
A customer reported that the default Invoice number database `wp_wcpdf_invoice_number` wasn't created on the new year change having:

* Plugin version: `2.11.4`
* Reset invoice number yearly: `enabled`

Only the table `wp_wcpdf_invoice_number_2021` was created and no additional logging data exists.

Forum topic: https://wordpress.org/support/topic/the-numbering-is-not-correlative/?view=all

**Comment by Spreeuw** [comment]
@alexmigf I believe the problem here is not so much related to the new year change or yearly reset, because the user also reports that disabling the reset and manually setting the next invoice number doesn't create the table either.

Customer reports there are no `wpo-wcpdf` logs. We do not do anything with the `$result` value [here](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/c66ad0f4e3cad139d142fea5d6854e9c316e5d64/includes/documents/class-wcpdf-sequential-number-store.php#L73-L84), logging could be helpful.

@alexmigf any other ideas? Do you think this could be related to #292? Query Monitor may reveal some database related errors?

**Comment by Spreeuw** [comment]
After sending a test version to the client with the default datetime value set to `1000-01-01`, they reported the table was create properly, this means that it was indeed #292 that was the issue here.
