### ISSUE TITLE
Add option to show/hide refund lines within invoice document.

### ISSUE THREAD

**Issue by smazur** [wpovernight/woocommerce-pdf-invoices-packing-slips#51]
Currently refund lines are forcibly removed from invoice total lines. It would be great to add an option into plugin settings to show or hide refunds. Thank you!

**Comment by Spreeuw** [comment]
Hi! I don't think this should be an option. An invoice is (or should be) _**immutable**_ after it has been issued. That is a legal requirement in most if not all countries around the world. This plugin uses WooCommerce order data as its source which is OK because once an order is paid, you can't edit the order data anymore. You can however still refund the order and doing so breaks the immutability if this would be reflected in the invoice. That's why the refund lines are removed from the invoice.

Instead, you should create a credit note/credit invoice that reflects the refunded amounts. This is not included in the free version of the plugin, but for the odd refund you can still do that manually outside of WooCommerce if the customer requests it or if you need it for your own accounting.
