### ISSUE TITLE
Overriding invoice template from a plugin

### ISSUE THREAD

**Issue by opportus** [wpovernight/woocommerce-pdf-invoices-packing-slips#53]
Hello,

I'm struggling at finding a hook that would allow me to override invoice template from my plugin.

I have found nothing in the doc and in the code neither.

Is it possible to achieve that?

Regards

**Comment by Spreeuw** [comment]
What exactly do you want to override? There are many filters & [action hooks](https://docs.wpovernight.com/woocommerce-pdf-invoices-packing-slips/pdf-template-action-hooks/) in the plugin that you can use. Additionally, you could either register your plugin folder so that the templates in it show up in the settings using the [`wpo_wcpdf_template_paths`](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/v2.1.10/includes/class-wcpdf-settings-general.php#L265) filter, or blindly replacing the file using the [`wpo_wcpdf_template_file`](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/v2.1.10/includes/documents/abstract-wcpdf-order-document.php#L605) filter.

**Comment by opportus** [comment]
Thanks @Spreeuw for your fast reply and your solutions.

The plugin is in charge to implement the business logic of my customer. Invoicing of this business is pretty much specific and uncommon, so template hooks don't help me much.

`wpo_wcpdf_template_paths` filter is exactly what I was looking for though. Thank you!
