### ISSUE TITLE
Feature request: add button to print all documents at once

### ISSUE THREAD

**Issue by squatto** [wpovernight/woocommerce-pdf-invoices-packing-slips#54]
I have a client that asked if there was any way to print both the invoice and the packing slip at the same time, in the same PDF file. They always print both, for every order, so the extra clicks and time it takes add up (eventually 😉)

I don't have the time right now to build it in, but if you'd prefer, I could add it in and PR it in a little bit. Let me know...thank you! And thank you for a wonderful plugin.

**Comment by Spreeuw** [comment]
I think this should be an add-on rather than a core function, as this is not something I have received other request for, and there are multiple potential issues with the filenaming, page numbering etc. You can hook into the `woocommerce_admin_order_actions_end` and add a button for the combined document (with the accompanying backend code for merging the docs).

**Comment by squatto** [comment]
@Spreeuw Right on, I'll look into building that out. Utilize `wcpdf_get_invoice()` and `wcpdf_get_packing_slip()` to do the actual PDF generation, correct?

**Comment by Spreeuw** [comment]
if you're going to merge the actual PDF files rather than merging the HTML beforehand, yes. Otherwise you could extend the bulk document class and call the templates instead. Good luck!

**Comment by squatto** [comment]
In the queue waiting to be reviewed for the plugin repo 👍🏻

https://github.com/squatto/woocommerce-pdf-invoices-packing-slips-print-all-documents

**Comment by Spreeuw** [comment]
That is nothing short of amazing work in such a short time :) 💯 
Can I hire you full time?

**Comment by squatto** [comment]
Thanks! When in doubt, build your own. haha

I'll shoot you an email 👍
