### ISSUE TITLE
wpo_wcpdf in uploads

### ISSUE THREAD

**Issue by davidhealey** [wpovernight/woocommerce-pdf-invoices-packing-slips#60]
Hi,

My malware scanner has flagged some of the files in this folder as containing executable code. Is it safe to delete these files? I assume they are not critical to the plugin since they are not in the plugin's folder.

Thanks.

**Comment by Spreeuw** [comment]
Can you name some of these files? The plugin needs to generate some php files from the fonts for usage in the PDF (these would be in the `/fonts` subfolder). The font PHP files are not executable in the sense that they contain any code that does anything, it simply returns a list of font metrics and does not display anything. This output is not readable from outside your website (even the font metrics it returns are not readable by outside processes). Feel free to delete anything in the `wpo_wcpdf` folder, but note that some files will always be regenerated when absent because they are required in the PDF generation process. Leaving them in the temp folder will prevent this regeneration and speed up the process.

**Comment by davidhealey** [comment]
Thanks for the quick reply. Yes all of the reported files are in the fonts folder, I'll just whitelist the folder.
