### ISSUE TITLE
Refund not shown on PDF invoice, even when invoice created after Refund was issued.

### ISSUE THREAD

**Issue by WebLenn** [wpovernight/woocommerce-pdf-invoices-packing-slips#649]
Our client reported an issue where the refund was not processed on the invoice which resulted in an incorrect invoice.

Our client has a product "Example product 1" which was ordered twice, our client doesn't have the product in stock so agreed with the customer to refund them, she did this in Woocommerce on the Processing order.

After the refund was processed our client changed the Order status to Completed ( the status on which the PDF is created ), the product that was refunded still noted quantity = 2, while in the backend order it was reset to quantity = 0.

How can we make sure these refunds are reflected on the invoice, the invoice is created only on the status completed and our client handles these refunds before changing the order status so If i'm correct this can't be because of legal reasons as stated in [another issue](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/issues/63).

**Comment by alexmigf** [comment]
Yes. The invoice does not show refund data, the credit note does. This is because we follow GAAP (Generally Accepted Accounting Principles) which means that administrative changes should be documented separately. This means that an original invoice should never be modified by a refund. In most countries (at least in the EU) this is even considered fraudulent (and illegal). We have chosen to follow this in both the free and the [paid extension](https://wpovernight.com/downloads/woocommerce-pdf-invoices-packing-slips-professional/).

**Comment by WebLenn** [comment]
Thanks for the clarification, I'll let our client know they simply need to use credit nota's for this.
