### ISSUE TITLE
PDF Attached to Processing Order Email empty due to missing Undefined property: WooCommerce_PDF_Invoices_Export::$output_body

### ISSUE THREAD

**Issue by garrett-eclipse** [wpovernight/woocommerce-pdf-invoices-packing-slips#7]
Hello,

I found the pdf attached to my Processing Order Email to the client was empty, in my logs I found the following errors;
[13-Aug-2015 07:43:19 UTC] PHP Notice:  Undefined property: WooCommerce_PDF_Invoices_Export::$output_body in /home/ljlee/public_html/wp-content/themes/ljlee/woocommerce/pdf/ljlee/html-document-wrapper.php on line 11

I found the issue was caused by the unset for output_body on line 279 in the process_template function within the class-wcpdf-export.php file;

```
// Try to clean up a bit of memory
unset($this->output_body);
```

Commenting this out resolved my issue and hasn't as yet caused any others.

Completing the order and admin emails all had the attachment without issue.

Thoughts?
Thanks

**Comment by Spreeuw** [comment]
Hi Garrett, Thanks for reporting.
That's an interesting situation - as you can see from the code, the $output_body is included into the template wrapper (#276) *before* it is unset (#279), so I don't see how this error got there. I haven't had any other reports of this either (20.000+ users). Did you make any changes to the code?

**Comment by garrett-eclipse** [comment]
Hi @Spreeuw, I haven't changed the core in any way aside form actions and filters in the template-functions file within my custom template. In there I use receipt.php rather than invoice.php, etc.
http://www.filedropper.com/ljlee

Hoping that's enough to reproduce and maybe point me in the right direction as to what went wrong. All other emails it's attached to and off the Order Received(Thank You), View Order and My Account pages the pdfs export fine.

Thanks

**Comment by Spreeuw** [comment]
I looked over your templates and template functions, but can't really see anything that could be related. I would test the templates, but because you use some theme specific functions I can't - even still I doubt that would help...

This absolutely has me puzzled! To my knowledge, PHP normally does not execute code before code before it is finished, yet that seems to be exactly what's happening on your site. Is this a custom PHP installation?
It's even more strange that this happens ONLY on the processing order email. There's nothing I can think of that makes this email special.

I would immediately apply your solution (removing the unset) if I wasn't already quite short on memory: dompdf is quite memory intensive and I need to free up as much space as I can.

**Comment by Spreeuw** [comment]
@garrett-eclipse do you still use this plugin? If so, it would be worth checking if our [latest beta](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/releases/tag/v2.0-beta-7) solves this issue (which is quite likely since it doesn't work with globals anymore).

**Comment by Spreeuw** [comment]
I'm closing this issue since this code has gone through major changes with version 2.0 and doesn't use globals anymore.
