### ISSUE TITLE
Add option to disable customer notes

### ISSUE THREAD

**Issue by Terminator-Barbapapa** [wpovernight/woocommerce-pdf-invoices-packing-slips#96]
Add option to disable customer notes on the invoice/packing slip templates. Option should be enabled by default.

**Comment by Spreeuw** [comment]
I see 2 options:

1. including the logic inside the template itself (requires updating all templates...)
2. change the return of the get_shipping_notes method based on the setting.

The downside of having to update templates is obvious.

The problem with 2. is that it doesn't work for custom documents that are not created by extending the class (e.g. retrieved with custom URLs). That's only relevant for a small group of people of course, but still.
We'd also need to be able to detect which documents have this setting implemented and which don't. That might be much more difficult to do.

Perhaps the best option would be to filter this option in the settings sanitization and to make sure it's ALWAYS set when saved, whether enabled (`1`) or not (`0`). That way you know that if it's `0`, the setting has been actively disabled, but if it's `null` or "not set", you can safely assume that it's enabled.

Of course the setting could also be reversed 'disable customer notes', but I'm not a fan of that UX wise.

**Comment by alexmigf** [comment]
I tried to implement this but I'm still a bit confused.

You want the setting to be "Enable customer notes" or "Disable customer notes"? Also, the checkbox callback always uses the value of `1` when is checked and `null` when is not, you said of using `0` is that right?

Do you want to use the filter inside an action on the `class-wcpdf-invoice.php`?

**Comment by Spreeuw** [comment]
> You want the setting to be "Enable customer notes" or "Disable customer notes"? 

I want the setting to be to enable the notes, and enabled by default.

> Also, the checkbox callback always uses the value of 1 when is checked and null when is not, you said of using 0 is that right?

This is not about the callback itself, but the setting as stored in the DB. Currently, a document setting that is governed by a checkbox is completely absent in the settings (so not even `null` but simply not set). If we set it to 0 when it is saved (by the user) as unchecked, we know that:

1. Not set means enabled (because they never saved this setting)
2. `1` means enabled
3. `0` means disabled

You would need to do this in the settings sanitization callback (preferably for this setting specifically!), making sure it is saved as 0 when not passed by the browser.

You could also bypass the above by running an update script, but this is not just about the settings in the options table, but also about the settings stored per order in the meta, so you would still need a way to handle those legacy settings... So that's not necesarily simpler.

**Comment by alexmigf** [comment]
I'm not getting how can i do this without using jQuery, because by default the checkbox should be checked to have the setting enabled, but the user can also uncheck it and i don't know when.

Scenario on first run without settings saved (option value is not set):
- Checkbox is checked (using $current = 0) and value is set to 0
   - If the user don't uncheck will be saved has 0
   - If the user uncheck will be saved has 0

**Comment by Spreeuw** [comment]
The value of the checkbox needs to be 1. That way, when the user saves the settings with the checkbox enabled, it is stored as 1 in the DB. If the settings are saved and the checkbox is not checked, you set the value to 0 in the settings sanitization callback, as I wrote above:

> You would need to do this in the settings sanitization callback (preferably for this setting specifically!), making sure it is saved as 0 when not passed by the browser.

That way you know that "not set" and "1" both mean **enabled**, and "0" means **disabled**.

**Comment by alexmigf** [comment]
Correct, but if i set the value to 1 and the user uncheck the input before saving the settings?

**Comment by Spreeuw** [comment]
The option should be to ENABLE the notes. So the `value` attribute of the checkbox is always 1. Then when the settings are saved (form is submitted), the browser will pass `1` for checked and nothing for unchecked. This way you know that when nothing is passed, you should save it as `0`. That's why you handle this in the sanitization callback before the options are saved.

**Comment by Spreeuw** [comment]
Seeing some issues with the approach of handling this via the default `sanitize_callback` because this callback only receives the raw data and no reference to the `$option` being filtered. This means that the only way to detect within that callback whether the 0 value should be saved is to check for another value that is (supposedly!) present in all documents and not other settings. That may not be reliable enough.

I see several alternative approaches. First of all, we could pass an argument to our checkbox method to indicate whether the unchecked value would need to be stored. This would benefit similar changes we would make in the future too.

**1. Using JS**
We can leave the name of the checkbox empty and toggle the value of a `hidden` input field to 0 or 1 depending on whether the checkbox is checked

**2. Multiple fields, using duplicate names**
If we generate two input fields, the first one hidden with value `0` and the second one being the checkbox with value `1`, I believe this would result in the server only reading the last one visible (so 1 if the checkbox is checked and 0 if not). I'm not 100% sure about compatibility of this option accross different servers/browsers etc.

**3. Multiple fields, using array names**
This one is more complex, it would look something like this:
```html
<input type="hidden" name="checkbox[checkbox_off]" value="0">
<input type="checkbox" name="checkbox[checkbox_on]" value="1">
```

then on the PHP side you could filter this more easily, because if the value is an array and the array has a key `checkbox_off` you know not to take the array value itself, but 0 or 1:
```php
if( is_array($input[$key]) && array_key_exists('checkbox_off',$input[$key]) ) {
    $output[$key] = isset($input[$key]['checkbox_on']) ? 1 : 0;
}
```

I'm not completely enthusiastic about any of these options though...

**Comment by alexmigf** [comment]
Using `$_POST` on the `sanitize_callback` we have this: `'option_page' => string 'wpo_wcpdf_documents_settings_invoice' (length=36)`

**Comment by Spreeuw** [comment]
Good catch! It's less portable/modular than option 4 though. Any thoughts/preferences?

**Comment by alexmigf** [comment]
If we plan to use more checkboxes like this probably 4 is better.

**Comment by Spreeuw** [comment]
It looks like you misinterpreted my suggestion. This should be one single settings callback to checkbox, and passing an extra arg to print the additional hidden field if that arg is enabled/set to true.
So instead of this:
```php
array(
	'type'			=> 'setting',
	'id'			=> 'display_customer_notes',
	'title'			=> __( 'Display customer notes', 'woocommerce-pdf-invoices-packing-slips' ),
	'callback'		=> 'checkbox',
	'section'		=> 'invoice',
	'args'			=> array(
		'option_name'		=> $option_name,
		'id'				=> 'display_customer_notes',
	)
),
```
you do:
```php
array(
	'type'			=> 'setting',
	'id'			=> 'display_customer_notes',
	'title'			=> __( 'Display customer notes', 'woocommerce-pdf-invoices-packing-slips' ),
	'callback'		=> 'checkbox',
	'section'		=> 'invoice',
	'args'			=> array(
		'option_name'		=> $option_name,
		'id'				=> 'display_customer_notes',
		'store_unchecked'	=> true,
	)
),
```
then when that argument is set you can print an _additional_ hidden input besides the checkbox within the current checkbox callback. That's much simpler because it doesn't require an additional settings call.
